const express = require('express')
const app = express()
const db = require('./db')
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.set("view engine", "hbs")
app.set('views',__dirname+ '/views')
app.listen(4444,()=>{
    console.log("server started on http://localhost:4444")
})
app.use('/pages', require('./routes/pages').route)
app.use('/api', require('./routes/api').route)
app.use('/', path.join(__dirname + 'public_static'))